using System.Collections.Generic;
using Unity.Networking.Transport;
using Unity.Networking.Transport.Relay;
using Unity.Collections;
using UnityEngine;
using Unity.Services.Relay;
using Unity.Services.Relay.Models;
using System.Buffers;
using System;
using System.Text;
using System.Collections.Concurrent;
using System.Threading.Tasks;

public class NetworkManager : MonoBehaviour
{
    #region Events
    /// <summary>
    /// Fired whenever the client has connected
    /// </summary>
    /// /// <param name="connectionId">Connection Id that Connected, 0 if client</param>
    public event Action<int> OnConnected;

    /// <summary>
    /// Fired whenever the client has disconnected
    /// </summary>
    /// /// /// <param name="connectionId">Connection Id that Disconnected, 0 if client</param>
    public event Action<int> OnDisconnected;

    /// <summary>
    /// Fired whenever there is a data sent from client or host
    /// </summary>
    /// <param name="data">Data sent</param>
    public event Action<NativeArray<byte>> OnBytesReceived;

    /// <summary>
    /// Fired when NetworkUpdate occurs
    /// </summary>
    public event Action OnNetworkUpdate;

    /// <summary>
    /// Fired when Unity Services (Authentication, Relay, etc.) have been successfully initialized.
    /// Subscribe to this event to perform actions once Unity Services are ready.
    /// </summary>
    public event Action OnUnityServiceInitialized;

    /// <summary>
    /// Fired when a Relay host has successfully created an allocation and generated a join code.
    /// The join code can be shared with other players to allow them to join the session.
    /// </summary>
    /// <param name="joinCode">The join code generated by the Relay service.</param>
    public event Action<string> OnJoinCodeGenerated;

    /// <summary>
    /// Fired whenever there is an error during Relay operations, such as initialization failure,
    /// host creation failure, or join failure. Use this to display error messages or log issues.
    /// </summary>
    /// <param name="errorMsg">A descriptive message indicating what went wrong with Relay.</param>
    public event Action<string> OnRelayError;
    #endregion

    #region Fields

    // Setup
    RelayHandler relayHandler = new();
    public NetworkDriver driver;
    NetworkConnection connection;
    NetworkPipeline reliablePipeline;

    // General
    public int connectionId { get; private set; } = 1;
    ushort relayPort = 0;
    public string joinCode { get; private set; } = "";
    public string ipAddress { get; private set; } = "127.0.0.1";
    public ushort localPort { get; private set; } = 7777;

    // Host
    Dictionary<int, NetworkConnection> connections = new();
    Dictionary<int, byte[]> bufferPayloads = new();
    Dictionary<int, byte[]> payloads = new();
    Dictionary<int, byte[]> reliableBufferPayloads = new();
    Dictionary<int, byte[]> reliablePayloads = new();
    int nextConnectionId = 2;
    int defaultNextConnectionId = 2;

    // Client
    List<PacketCodec.Packet> bufferPackets = new();
    List<PacketCodec.Packet> packets = new();
    List<PacketCodec.Packet> reliableBufferPackets = new();
    List<PacketCodec.Packet> reliablePackets = new();

    // Server State
    public bool IsHost { get; private set; } = false;
    public bool IsClient { get; private set; } = false;
    public bool IsStarted { get { return (IsHost || IsClient); } }
    public int PlayerCount { get { return connections.Count + 1; } }

    // Network Update
    [Header("Network Update")]
    public bool enableNetworkUpdate = true;
    public float networkUpdatePerSecond = 20f;
    float networkDelta;

    // --- Singleton ---
    public static NetworkManager networkManager { get; private set; }

    #endregion

    #region Helpers
    // --- HELPERS ---
    public static NativeList<byte> ToNativeList(byte[] data, Allocator allocator)
    {
        var list = new NativeList<byte>(allocator);

        using (var temp = new NativeArray<byte>(data, Allocator.Temp))
        {
            list.AddRange(temp);
        }

        return list;
    }


    // --- Payload Management

    void AppendPayload(int connectionId, byte[] data)
    {
        if (connectionId == 1)
        {
            var native = new NativeArray<byte>(data, Allocator.Temp);
            OnBytesReceived?.Invoke(native);
            return;
        }

        if (data == null || data.Length == 0)
            return;

        if (!bufferPayloads.TryGetValue(connectionId, out var buffer) || buffer == null || buffer.Length == 0)
        {
            // first payload = just store it
            bufferPayloads[connectionId] = data;
            return;
        }

        // merge old + new
        byte[] merged = new byte[buffer.Length + data.Length];

        Buffer.BlockCopy(buffer, 0, merged, 0, buffer.Length);
        Buffer.BlockCopy(data, 0, merged, buffer.Length, data.Length);

        bufferPayloads[connectionId] = merged;
    }

    void AppendReliablePayload(int connectionId, byte[] data)
    {
        if (connectionId == 1)
        {
            var native = new NativeArray<byte>(data, Allocator.Temp);
            OnBytesReceived?.Invoke(native);
            return;
        }

        if (data == null || data.Length == 0)
            return;

        if (!reliableBufferPayloads.TryGetValue(connectionId, out var buffer) || buffer == null || buffer.Length == 0)
        {
            // first payload = just store it
            reliableBufferPayloads[connectionId] = data;
            return;
        }

        // merge old + new
        byte[] merged = new byte[buffer.Length + data.Length];

        Buffer.BlockCopy(buffer, 0, merged, 0, buffer.Length);
        Buffer.BlockCopy(data, 0, merged, buffer.Length, data.Length);

        reliableBufferPayloads[connectionId] = merged;
    }

    void AppendAllPayloadsExcept(int connectionId, byte[] data)
    {
        foreach (var kvp in payloads)
        {
            if (kvp.Key == connectionId) continue;
            AppendPayload(kvp.Key, data);
        }
    }

    void AppendAllReliablePayloadsExcept(int connectionId, byte[] data)
    {
        foreach (var kvp in payloads)
        {
            if (kvp.Key == connectionId) continue;
            AppendReliablePayload(kvp.Key, data);
        }
    }

    void AppendAllPayloads(byte[] data)
    {
        foreach (var kvp in payloads)
        {
            AppendPayload(kvp.Key, data);
        }
    }

    void ClearPayload(int connectionId)
    {
        payloads[connectionId] = new byte[] { };
    }
    
    bool AreAllPayloadsEmpty()
    {
        bool allEmpty = true;

        foreach (var kvp in payloads)
        {
            if (kvp.Value.Length > 0)
            {
                allEmpty = false;
                break;
            }
        }
        return allEmpty;
    }

    bool AreAllReliablePayloadsEmpty()
    {
        bool allEmpty = true;

        foreach (var kvp in reliablePayloads)
        {
            if (kvp.Value.Length > 0)
            {
                allEmpty = false;
                break;
            }
        }
        return allEmpty;
    }

    void AppendBufferPayloads()
    {
        foreach (var kvp in bufferPayloads)
        {
            int key = kvp.Key;
            byte[] buffer = kvp.Value;

            if (buffer == null || buffer.Length == 0)
                continue;

            // FIRST TIME: just move buffer into payload
            if (!payloads.TryGetValue(key, out var main) || main == null || main.Length == 0)
            {
                payloads[key] = buffer;
                continue;
            }

            // APPEND: merge arrays
            byte[] merged = new byte[main.Length + buffer.Length];

            Buffer.BlockCopy(main, 0, merged, 0, main.Length);
            Buffer.BlockCopy(buffer, 0, merged, main.Length, buffer.Length);

            payloads[key] = merged;
        }

        // CLEAR buffers (replace with empty arrays or null)
        var keys = new List<int>(bufferPayloads.Keys);
        foreach (var key in keys)
        {
            bufferPayloads[key] = Array.Empty<byte>();
        }

        // === RELIABLE ===

        foreach (var kvp in reliableBufferPayloads)
        {
            int key = kvp.Key;
            byte[] buffer = kvp.Value;

            if (buffer == null || buffer.Length == 0)
                continue;

            // FIRST TIME: just move buffer into payload
            if (!reliablePayloads.TryGetValue(key, out var main) || main == null || main.Length == 0)
            {
                reliablePayloads[key] = buffer;
                continue;
            }

            // APPEND: merge arrays
            byte[] merged = new byte[main.Length + buffer.Length];

            Buffer.BlockCopy(main, 0, merged, 0, main.Length);
            Buffer.BlockCopy(buffer, 0, merged, main.Length, buffer.Length);

            reliablePayloads[key] = merged;
        }

        // CLEAR buffers (replace with empty arrays or null)
        var reliableKeys = new List<int>(reliableBufferPayloads.Keys);
        foreach (var key in reliableKeys)
        {
            reliableBufferPayloads[key] = Array.Empty<byte>();
        }
    }

    void AppendBufferPackets()
    {
        packets.AddRange(bufferPackets);
        bufferPackets.Clear();
        reliablePackets.AddRange(reliableBufferPackets);
        reliableBufferPackets.Clear();
    }


    // --- RECEIVE ---

    void HostReceiveData()
    {
        DataStreamReader stream;
        NetworkEvent.Type evt;
        foreach (var kvpConnection in connections)
        {
            var targetKey = kvpConnection.Key;
            var targetConnection = kvpConnection.Value;
            if (!targetConnection.IsCreated) continue;

            while ((evt = targetConnection.PopEvent(driver, out stream)) != NetworkEvent.Type.Empty)
            {
                switch (evt)
                {
                    case NetworkEvent.Type.Data:
                        // Allocate a NativeArray of the correct length
                        NativeArray<byte> receivedData = new NativeArray<byte>(stream.Length, Allocator.Temp);

                        // Copy bytes from the DataStreamReader into the NativeArray
                        stream.ReadBytes(receivedData);
                        HostHandleReceivedData(receivedData);
                        break;
                    case NetworkEvent.Type.Connect:
                        //Debug.Log("Player Connected!");
                        //OnConnected?.Invoke(targetKey);
                        break;
                    case NetworkEvent.Type.Disconnect:
                        connection = default; // mark connection as disconnected
                        Debug.Log("Player Disconnected!");
                        OnDisconnected?.Invoke(targetKey);
                        break;
                }
            }
        }
    }

    void HostHandleReceivedData(NativeArray<byte> data)
    {
        // Get Byte Intent
        // 1 = Set ConnectionId
        // 2 = OnByteReceived
        byte intent = data[0];
        int payloadSize = data.Length - 1;
        NativeArray<byte> payload =
            new NativeArray<byte>(payloadSize, Allocator.Temp);
        NativeArray<byte>.Copy(
            data,
            1,
            payload,
            0,
            payloadSize
        );

        switch (intent)
        {
            case 1:
                DataStreamReader reader = new DataStreamReader(payload);
                reader.ReadInt();
                break;
            case 2:
                HostHandlePacket(payload);
                break;
            default:
                break;
        }
    }

    void HostHandlePacket(NativeArray<byte> payload)
    {
        var reader = new DataStreamReader(payload);
        PacketCodec.Packet packet;
        // int loopCounter = 0;
        while (PacketCodec.ReadNext(ref reader, out packet))
        {
            if (packet.payload == null || packet.payload.Length == 0)
                continue;
            int loopCounter = 0;
            string message = "";
            DataStreamReader payloadReader = new DataStreamReader(new NativeArray<byte>(packet.payload, Allocator.Temp));
            while (payloadReader.Length - payloadReader.GetBytesRead() > 0)
            {
                if (loopCounter >= 1000)
                {
                    print("LOOP DETECTED IN NETWORK MANAGER");
                    break;
                }
                loopCounter++;
                message += $"[{payloadReader.ReadByte()}]";
            }
            //print($"Packet connectionId: {packet.connectionId} type: {packet.type} message: {message}");
            switch (packet.type)
            {
                case 1:
                    AppendPayload(packet.connectionId, packet.payload);
                    break;

                case 2:
                    AppendAllPayloads(packet.payload);
                    break;

                case 3:
                    AppendAllPayloadsExcept(packet.connectionId, packet.payload);
                    break;
            }
        }
    }

    void ClientReceiveData()
    {
        if (!connection.IsCreated) return;

        DataStreamReader stream;
        NetworkEvent.Type evt;

        while ((evt = connection.PopEvent(driver, out stream)) != NetworkEvent.Type.Empty)
        {
            switch (evt)
            {
                case NetworkEvent.Type.Data:
                    // Allocate a NativeArray of the correct length
                    NativeArray<byte> receivedData = new NativeArray<byte>(stream.Length, Allocator.Temp);

                    // Copy bytes from the DataStreamReader into the NativeArray
                    stream.ReadBytes(receivedData);
                    ClientHandleReceivedData(receivedData);
                    break;
                case NetworkEvent.Type.Connect:
                    Debug.Log("Connected to host!");
                    OnConnected?.Invoke(0);
                    break;
                case NetworkEvent.Type.Disconnect:
                    Debug.Log("Disconnected from host!");
                    OnDisconnected?.Invoke(0);
                    break;
            }
        }
    }

    void ClientHandleReceivedData(NativeArray<byte> data)
    {
        // Get Byte Intent
        // 1 = Set ConnectionId
        // 2 = OnByteReceived
        byte intent = data[0];
        int payloadSize = data.Length - 1;
        NativeArray<byte> payload =
            new NativeArray<byte>(payloadSize, Allocator.Temp);
        NativeArray<byte>.Copy(
            data,
            1,
            payload,
            0,
            payloadSize
        );

        switch (intent)
        {
            case 1:
                DataStreamReader reader = new DataStreamReader(payload);
                connectionId = reader.ReadInt();
                Debug.Log($"ConnectionId is now: {connectionId}");
                break;
            case 2:
                OnBytesReceived?.Invoke(payload);
                break;
            default:
                break;
        }

    }


    // --- SEND ---

    void HostSendPayloads()
    {
        if (!driver.IsCreated)
            return;

        if (!AreAllPayloadsEmpty())
        {
            // Snapshot keys only (NOT deep copy of data)
            var keys = new List<int>(payloads.Keys);

            foreach (var key in keys)
            {
                if (!payloads.TryGetValue(key, out var data) || data.Length == 0)
                    continue;

                if (key == connectionId)
                {
                    var native = new NativeArray<byte>(data, Allocator.Temp);
                    OnBytesReceived?.Invoke(native);
                }
                else
                {
                    connections.TryGetValue(key, out var targetConnection);

                    if (driver.BeginSend(targetConnection, out var writer) == 0)
                    {
                        writer.WriteByte(2);
                        writer.WriteBytes(data);
                        driver.EndSend(writer);
                    }
                }

                // Clear AFTER sending (important change)
                payloads[key] = new byte[] { };
            }
        }

        if (!AreAllReliablePayloadsEmpty())
        {
            // Snapshot keys only (NOT deep copy of data)
            var keys = new List<int>(reliablePayloads.Keys);

            foreach (var key in keys)
            {
                if (!reliablePayloads.TryGetValue(key, out var data) || data.Length == 0)
                    continue;

                if (key == connectionId)
                {
                    var native = new NativeArray<byte>(data, Allocator.Temp);
                    OnBytesReceived?.Invoke(native);
                }
                else
                {
                    connections.TryGetValue(key, out var targetConnection);

                    if (driver.BeginSend(reliablePipeline, targetConnection, out var writer) == 0)
                    {
                        writer.WriteByte(2);
                        writer.WriteBytes(data);
                        driver.EndSend(writer);
                    }
                }

                // Clear AFTER sending (important change)
                reliablePayloads[key] = new byte[] { };
            }
        }
    }

    void ClientSendPayload()
    {
        if (!driver.IsCreated)
            return;

        if (connection == default)
            return;

        if (packets.Count != 0)
        {

            if (driver.BeginSend(connection, out var writer) != 0)
                return;

            writer.WriteByte(2);

            foreach (var packet in packets)
            {
                // print($"packet type: {packet.type} packet connectionId: {packet.connectionId}");
                if (!(packet.payload != null && packet.payload.Length > 0) || packet.payload.Length == 0)
                    continue;

                switch (packet.type)
                {
                    case 1:
                        PacketCodec.WriteSend(ref writer, packet.connectionId, packet.payload);
                        break;

                    case 2:
                        PacketCodec.WriteSendToAll(ref writer, packet.payload);
                        break;

                    case 3:
                        PacketCodec.WriteSendToAllExcept(ref writer, packet.connectionId, packet.payload);
                        break;
                }
            }

            driver.EndSend(writer);

            packets.Clear();
        }

        if (reliablePackets.Count != 0)
        {

            if (driver.BeginSend(reliablePipeline, connection, out var writer) != 0)
                return;

            writer.WriteByte(2);

            foreach (var packet in reliablePackets)
            {
                // print($"packet type: {packet.type} packet connectionId: {packet.connectionId}");
                if (!(packet.payload != null && packet.payload.Length > 0) || packet.payload.Length == 0)
                    continue;

                switch (packet.type)
                {
                    case 1:
                        PacketCodec.WriteSend(ref writer, packet.connectionId, packet.payload);
                        break;

                    case 2:
                        PacketCodec.WriteSendToAll(ref writer, packet.payload);
                        break;

                    case 3:
                        PacketCodec.WriteSendToAllExcept(ref writer, packet.connectionId, packet.payload);
                        break;
                }
            }

            driver.EndSend(writer);

            reliablePackets.Clear();
        }
    }


    // --- SPECIAL ---

    void AcceptClients()
    {
        NetworkConnection newConnection;
        while ((newConnection = driver.Accept()) != default(NetworkConnection))
        {

            int connectionId = nextConnectionId;
            nextConnectionId++;
            connections.Add(connectionId, newConnection);

            if (driver.BeginSend(reliablePipeline, newConnection, out var writer) == 0)
            {
                writer.WriteByte(1); // Intent
                writer.WriteInt(connectionId);
                writer.WriteShort((short)connections.Count);
                foreach (var kvp in connections)
                {
                    writer.WriteInt(kvp.Key);
                }
                writer.WriteInt(connectionId);
                driver.EndSend(writer);
                Debug.Log("Client connected! Total clients: " + connections.Count);
                OnConnected?.Invoke(connectionId);
            }
            else
            {
                Debug.LogWarning($"Failed to send connection ID to client {connectionId}");
            }
        }
    }

    void Shutdown()
    {
        if (driver.IsCreated)
        {
            driver.Dispose();
        }
    }

    void SyncPayloadsWithConnections()
    {
        if (!IsHost) return;

        // Remove payloads for disconnected clients
        List<int> toRemove = new();

        foreach (var kvp in payloads)
        {
            if (kvp.Key == 1) continue;
            if (!connections.ContainsKey(kvp.Key))
            {
                // handle join
                toRemove.Add(kvp.Key);
            }
        }

        foreach (int id in toRemove)
        {
            payloads.Remove(id);
        }

        // Ensure every connection has a payload buffer
        foreach (var connection in connections)
        {
            int id = connection.Key;

            if (!payloads.ContainsKey(id))
            {
                payloads[id] = Array.Empty<byte>();
            }
        }

        if (!payloads.ContainsKey(1))
        {
            payloads[1] = Array.Empty<byte>();
        }
    }

    void RemoveNonConnections()
    {
        List<int> disconnectedKeys = new List<int>();
        foreach (var kvp in connections)
        {
            int clientId = kvp.Key;
            NetworkConnection targetconnection = kvp.Value;
            if (!targetconnection.IsCreated)
            {
                // Mark disconnected clients for removal
                disconnectedKeys.Add(clientId);
            }
        }
        // Remove disconnected clients
        foreach (var key in disconnectedKeys)
        {
            connections.Remove(key);
        }
    }

    bool StartHosting(ushort port)
    {
        if (driver.Bind(NetworkEndpoint.AnyIpv4.WithPort(port)) != 0)
        {
            Debug.LogError("Host failed to bind");
            return false;
        }

        if (driver.Listen() != 0)
        {
            Debug.LogError("Host failed to listen");
            return false;
        }

        Debug.Log($"Host is now listening on port {port}");

        connectionId = 1;
        IsHost = true;

        return true;
    }
    #endregion

    #region Public Functions

    // --- Initialize ---

    /// <summary>
    /// Initializes Unity Services if they have not already been initialized. This must be called before hosting or connecting to a Relay session. Calling it multiple times is safe and will not reinitialize an already initialized service.
    /// </summary>
    public async void Init()
    {
        await relayHandler.InitUnityServices();
    }


    // --- Hosting, Connecting and Disconnecting ---

    /// <summary>
    /// Creates a Unity Relay allocation, retrieves a join code, configures the transport, and starts listening for incoming client connections. The local player becomes the host/server. 
    /// </summary>
    public async void Host()
    {
        RelayServerData rsd = await relayHandler.HostRelay();
        var settings = new NetworkSettings();
        settings.WithRelayParameters(ref rsd);

        driver = NetworkDriver.Create(settings);
        reliablePipeline = driver.CreatePipeline(typeof(ReliableSequencedPipelineStage));

        if (!StartHosting(relayPort)) { return; }

        Debug.Log("Relay Host is now listening on port " + relayPort);
        joinCode = relayHandler.joinCode;
    }

    /// <summary>
    /// Starts a local host using Unity Transport without Relay.
    /// Creates a NetworkDriver, binds to the configured port,
    /// and begins listening for incoming client connections.
    /// </summary>
    public void HostLocal()
    {
        driver = NetworkDriver.Create();
        reliablePipeline = driver.CreatePipeline(typeof(ReliableSequencedPipelineStage));

        if (!StartHosting(localPort)) { return; }

        Debug.Log($"Host is now listening on port {localPort}");
    }

    /// <summary>
    /// Terminates the Relay allocation, disconnects all connected clients, stops accepting new connections, and clears host-side networking resources.
    /// </summary>
    public void StopHost()
    {
        // Disconnect all remote clients
        foreach (var connection in connections)
        {
            connection.Value.Disconnect(driver);
        }

        connections.Clear();

        // Close server socket
        driver.Dispose();

        // Reset state
        IsHost = false;
    }

    /// <summary>
    /// Stores a Relay join code that will be used by Connect(). Useful when separating UI input from connection logic.
    /// </summary>
    /// <param name="joinCode">The Unity Relay join code to store for a future connection attempt. Usually obtained from a host and shared with clients.</param>
    public void SetJoinCode(string joinCode)
    {
        this.joinCode = joinCode;
    }

    /// <summary>
    /// Stores the IP address that will be used by IP-based connection methods.
    /// </summary>
    /// <param name="ipAddress">The target IPv4 or IPv6 address of the host to connect to.</param>
    public void SetIP(string ipAddress)
    {
        this.ipAddress = ipAddress;
    }

    /// <summary>
    /// Stores the port number that will be used by IP-based connection methods.
    /// </summary>
    /// <param name="port">The network port as a string value.</param>
    public void SetPort(string port)
    {
        localPort = ushort.Parse(port);
    }

    /// <summary>
    /// Stores the port number that will be used by IP-based connection methods.
    /// </summary>
    /// <param name="port">The network port number.</param>
    public void SetPort(ushort port)
    {
        localPort = port;
    }

    /// <summary>
    /// Connects to a Relay host using the join code previously provided through SetJoinCode().
    /// </summary>
    public async void Connect()
    {
        await Connect(joinCode);
    }

    /// <summary>
    /// Joins a Relay session using the supplied join code. This overload combines setting the join code and connecting in a single call.
    /// </summary>
    /// <param name="joinCode">The Unity Relay join code of the host session to join. This value is used immediately for the connection attempt.</param>
    public async Task Connect(string joinCode)
    {
        RelayServerData rsd = await relayHandler.JoinRelay(joinCode);
        var settings = new NetworkSettings();
        settings.WithRelayParameters(ref rsd);

        driver = NetworkDriver.Create(settings);
        reliablePipeline = driver.CreatePipeline(typeof(ReliableSequencedPipelineStage));

        // Clients only connect (no bind needed for Relay).
        connection = driver.Connect();

        Debug.Log("Player client connecting to Relay server...");
        IsClient = true;
    }

    /// <summary>
    /// Connects to a locally hosted server using the currently configured local network settings.
    /// Useful for local testing and development on the same machine or LAN.
    /// </summary>
    public async void ConnectLocal()
    {
        await ConnectIP("127.0.0.1", localPort);
    }

    /// <summary>
    /// Connects to a host using the specified IP address and the currently configured port.
    /// </summary>
    /// <param name="ipAddress">The IP address of the host to connect to.</param>
    public async void ConnectIP(string ipAddress)
    {
        await ConnectIP(ipAddress, localPort);
    }

    /// <summary>
    /// Connects directly to a host using the specified IP address and port.
    /// This overload bypasses any previously stored connection settings.
    /// </summary>
    /// <param name="ipAddress">The IP address of the host to connect to.</param>
    /// <param name="port">The network port on which the host is listening.</param>
    public async Task ConnectIP(string ipAddress, ushort port)
    {
        var settings = new NetworkSettings();

        driver = NetworkDriver.Create(settings);
        reliablePipeline = driver.CreatePipeline(typeof(ReliableSequencedPipelineStage));

        // Parse IP
        var endpoint = NetworkEndpoint.Parse(ipAddress, port);

        connection = driver.Connect(endpoint);

        Debug.Log($"Client connecting to {ipAddress}:{port} ...");

        IsClient = true;

        await Task.CompletedTask;
    }

    /// <summary>
    /// Gracefully disconnects from the host, releases networking resources, clears connection state, and stops receiving network messages.
    /// </summary>
    public void Disconnect()
    {
        connection.Disconnect(driver);
        connectionId = 1;
        nextConnectionId = defaultNextConnectionId;
    }


    // --- Process ---

    /// <summary>
    /// Performs a single networking update cycle. This processes incoming packets, connection events, disconnection events, and outgoing messages. Use this manually if automatic updates are disabled.
    /// </summary>
    public void NetworkUpdate()
    {
        if (IsHost)
        {
            // 1. merge buffered input
            AppendBufferPayloads();

            // 2. sync connection state BEFORE sending
            SyncPayloadsWithConnections();

            // 3. send
            HostSendPayloads();

            // 4. cleanup
            RemoveNonConnections();
        }

        if (IsClient)
        {
            AppendBufferPackets();
            ClientSendPayload();
        }

        OnNetworkUpdate?.Invoke();
    }


    // --- For PlayerObjects ---

    /// <summary>
    /// Queues a byte payload to the specified connection. Typically used by the host to send data to an individual client.
    /// </summary>
    /// <param name="connectionId">The target connection identifier that should receive the data. Typically assigned by the networking system when a client connects.</param>
    /// <param name="data">The raw payload to send. Can contain serialized game state, RPC data, chat messages, or any custom packet format.</param>
    public void WriteDataTo(int connectionId, byte[] data)
    {
        if (IsHost)
        {
            AppendPayload(connectionId, data);
        }
        if (IsClient)
        {
            PacketCodec.Packet packet = new PacketCodec.Packet
            { connectionId = connectionId, payload = data, type = 1 };
            bufferPackets.Add(packet);
        }
    }

    /// <summary>
    /// Queues a "guaranteed" byte payload to the specified connection. Typically used by the host to send data to an individual client.
    /// </summary>
    /// <param name="connectionId">The target connection identifier that should receive the data. Typically assigned by the networking system when a client connects.</param>
    /// <param name="data">The raw payload to send. Can contain serialized game state, RPC data, chat messages, or any custom packet format.</param>
    public void WriteReliableDataTo(int connectionId, byte[] data)
    {
        if (IsHost)
        {
            AppendReliablePayload(connectionId, data);
        }
        if (IsClient)
        {
            PacketCodec.Packet packet = new PacketCodec.Packet
            { connectionId = connectionId, payload = data, type = 1 };
            reliableBufferPackets.Add(packet);
        }
    }

    /// <summary>
    /// Sends a byte payload to every connected client except the local connection. Useful for relaying state updates received from one client to all other clients.
    /// </summary>
    /// <param name="data">The raw payload to broadcast to all connected remote clients except the local connection. Commonly used by a host to relay client messages to everyone else.</param>
    public void WriteDataToAllExceptSelf(byte[] data)
    {
        if (IsHost)
        {
            AppendAllPayloadsExcept(connectionId, data);
        }
        if (IsClient)
        {
            PacketCodec.Packet packet = new PacketCodec.Packet
            { connectionId = connectionId, payload = data, type = 3 };
            bufferPackets.Add(packet);
        }
    }

    /// <summary>
    /// Sends a reliable byte payload to every connected client except the local connection. Useful for relaying "guaranteed" state updates received from one client to all other clients.
    /// </summary>
    /// <param name="data">The raw payload to broadcast to all connected remote clients except the local connection. Commonly used by a host to relay client messages to everyone else.</param>
    public void WriteReliableDataToAllExceptSelf(byte[] data)
    {
        if (IsHost)
        {
            AppendAllReliablePayloadsExcept(connectionId, data);
        }
        if (IsClient)
        {
            PacketCodec.Packet packet = new PacketCodec.Packet
            { connectionId = connectionId, payload = data, type = 3 };
            reliableBufferPackets.Add(packet);
        }
    }

    #endregion

    #region Listeners
    void Awake()
    {
        DontDestroyOnLoad(gameObject); // Persist across scenes
    }

    void Start()
    {
        relayHandler.OnUnityServiceInitialized += () => OnUnityServiceInitialized?.Invoke();
        relayHandler.OnJoinCodeGenerated += (string val) => OnJoinCodeGenerated?.Invoke(val);
        relayHandler.OnRelayError += (string val) => OnRelayError?.Invoke(val);
    }

    void Update()
    {
        if (!driver.IsCreated)
            return;

        driver.ScheduleUpdate().Complete();

        if (enableNetworkUpdate)
        {
            networkDelta += Time.deltaTime;
            float interval = 1f / networkUpdatePerSecond;

            // FIXED TICK LOOP FIRST (deterministic network step)
            while (networkDelta >= interval)
            {
                networkDelta -= interval;
                NetworkUpdate();
            }
        }

        // RECEIVE ALWAYS AFTER DRIVER UPDATE
        if (IsHost)
        {
            HostReceiveData();
            AcceptClients();
        }

        if (IsClient)
        {
            ClientReceiveData();
        }
    }

    void OnDestroy()
    {
        Shutdown();
    }

    void OnApplicationQuit()
    {
        Shutdown();
    }
    #endregion
}