using System;
using System.Collections.Generic;
using UnityEngine;
using Unity.Services.Core;
using Unity.Services.Authentication;
using Unity.Services.Relay;
using Unity.Services.Relay.Models;
using Unity.Networking.Transport;
using Unity.Networking.Transport.Relay;
using System.Linq;
using System.Threading.Tasks;
using Unity.Collections;

public class RelayHandler
{
    #region Events
    /// <summary>
    /// Fired when Unity Services (Authentication, Relay, etc.) have been successfully initialized.
    /// Subscribe to this event to perform actions once Unity Services are ready.
    /// </summary>
    public event Action OnUnityServiceInitialized;

    /// <summary>
    /// Fired when a Relay host has successfully created an allocation and generated a join code.
    /// The join code can be shared with other players to allow them to join the session.
    /// </summary>
    /// <param name="joinCode">The join code generated by the Relay service.</param>
    public event Action<string> OnJoinCodeGenerated;

    /// <summary>
    /// Fired whenever there is an error during Relay operations, such as initialization failure,
    /// host creation failure, or join failure. Use this to display error messages or log issues.
    /// </summary>
    /// <param name="errorMsg">A descriptive message indicating what went wrong with Relay.</param>
    public event Action<string> OnRelayError;
    #endregion

    #region Fields
    private const string connectionType = "dtls";
    public bool unityServiceInitialized { get { return (UnityServices.State == ServicesInitializationState.Initialized); } }
    public List<string> regionIds { get; private set; } = new List<string>();
    public string joinCode { get; private set; } = "";
    public RelayServerData relayData { get; private set; }

    private Allocation hostAllocation;
    private JoinAllocation joinAllocation;
    #endregion

    #region Initialize Unity Services
    /// <summary>
    /// Initialize Unity Services, which allows the use of Unity Relay
    /// </summary>
    public async Task InitUnityServices()
    {
        try
        {
            if (UnityServices.State == ServicesInitializationState.Initialized) return;
            await UnityServices.InitializeAsync();
            await AuthenticationService.Instance.SignInAnonymouslyAsync();
            Debug.Log("Unity Services Initialized");
            OnUnityServiceInitialized?.Invoke();
        }
        catch (Exception e)
        {
            Debug.LogError($"Unity Services init error: {e.Message}");
            OnRelayError?.Invoke(e.Message);
        }
    }
    #endregion

    #region Get Regions
    /// <summary>
    /// Retrieves all available Relay regions from Unity Relay service.
    /// Fires the OnRegionsRetrieved event when done.
    /// </summary>
    public async Task<List<string>> GetRegions()
    {
        try
        {
            var regions = await RelayService.Instance.ListRegionsAsync();
            regionIds = regions.Select(r => r.Id).ToList();
        }
        catch (Exception e)
        {
            Debug.LogError($"Failed to get Relay regions: {e.Message}");
            OnRelayError?.Invoke(e.Message);
        }
        return regionIds;
    }
    #endregion

    #region Host Relay
    /// <summary>
    /// Hosts a Relay server with the specified maximum connections and region.
    /// </summary>
    /// <param name="maxConnections">Maximum number of players including host</param>
    /// <param name="region">Region ID string to host in (optional, can be null)</param>
    public async Task<RelayServerData> HostRelay(int maxConnections = 2, string region = null)
    {
        try
        {
            // 1. Create a host allocation
            hostAllocation = await RelayService.Instance.CreateAllocationAsync(maxConnections, region);

            // 2. Get join code for clients
            joinCode = await RelayService.Instance.GetJoinCodeAsync(hostAllocation.AllocationId);
            Debug.Log($"Relay Host Created in region {region ?? "default"}. Join Code: {joinCode}");
            OnJoinCodeGenerated?.Invoke(joinCode);


            // 3. Create RelayServerData with correct protocol (udp is recommended for Unity 2021.3)
            relayData = AllocationUtils.ToRelayServerData(hostAllocation, connectionType);

            Debug.Log($"Endpoint: {relayData.Endpoint}");
            Debug.Log($"AllocationId: {relayData.AllocationId}");
        }
        catch (Exception e)
        {
            Debug.LogError($"Host Relay Error: {e.Message}");
            OnRelayError?.Invoke(e.Message);
        }

        // 4. Pass it to your network manager to create driver, bind, and listen
        return relayData;
    }
    #endregion

    #region Join Relay
    public async Task<RelayServerData> JoinRelay(string joinCode)
    {
        Debug.Log(joinCode);
        try
        {
            joinAllocation = await RelayService.Instance.JoinAllocationAsync(joinCode);

            if (joinAllocation == null) throw new Exception("JoinAllocation failed");
            
            relayData = relayData = AllocationUtils.ToRelayServerData(joinAllocation, connectionType);
            Debug.Log("Joined Relay Server");
        }
        catch (Exception e)
        {
            Debug.LogError($"Join Relay Error: {e.Message}");
            OnRelayError?.Invoke(e.Message);
        }

        return relayData;
    }
    #endregion
}