using System;
using System.Collections.Generic;
using UnityEngine;
using Unity.Services.Core;
using Unity.Services.Authentication;
using Unity.Services.Relay;
using Unity.Services.Relay.Models;
using Unity.Networking.Transport;
using Unity.Networking.Transport.Relay;
using System.Linq;
using System.Threading.Tasks;
using Unity.Collections;

public class NetworkDriverManager
{
    #region Events
    /// <summary>
    /// Fired whenever the client has connected
    /// </summary>
    /// /// <param name="connectionId">Connection Id that Connected, 0 if client</param>
    public event Action<int> OnConnected;

    /// <summary>
    /// Fired whenever the client has disconnected
    /// </summary>
    /// /// /// <param name="connectionId">Connection Id that Disconnected, 0 if client</param>
    public event Action<int> OnDisconnected;

    /// <summary>
    /// Fired whenever there is a data sent from client or host
    /// </summary>
    /// <param name="data">Data sent</param>
    public event Action<NativeArray<byte>> OnBytesReceived;

    /// <summary>
    /// Fired when Unity Services (Authentication, Relay, etc.) have been successfully initialized.
    /// Subscribe to this event to perform actions once Unity Services are ready.
    /// </summary>
    public event Action OnUnityServiceInitialized;

    /// <summary>
    /// Fired when a Relay host has successfully created an allocation and generated a join code.
    /// The join code can be shared with other players to allow them to join the session.
    /// </summary>
    /// <param name="joinCode">The join code generated by the Relay service.</param>
    public event Action<string> OnJoinCodeGenerated;

    /// <summary>
    /// Fired whenever there is an error during Relay operations, such as initialization failure,
    /// host creation failure, or join failure. Use this to display error messages or log issues.
    /// </summary>
    /// <param name="errorMsg">A descriptive message indicating what went wrong with Relay.</param>
    public event Action<string> OnRelayError;
    #endregion

    #region Fields
    RelayProvider relayProvider;
    public MessageRouter messageRouter;
    public ConnectionManager connectionManager;
    public NetworkDriver driver;
    public NetworkConnection connection { get { return connectionManager.connection; } }
    public NetworkPipeline reliablePipeline;

    // Host
    public Dictionary<int, NetworkConnection> connections { get { return connectionManager.connections; } }

    // Server State
    public bool IsHost { get; private set; } = false;
    public bool IsClient { get; private set; } = false;
    public bool IsStarted { get { return (IsHost || IsClient); } }
    public int PlayerCount { get { return connectionManager.connections.Count + 1; } }

    // General
    public int connectionId { get { return connectionManager.connectionId; } }
    ushort relayPort = 0;
    public string joinCode { get; private set; } = "NULL";
    public string ipAddress { get; private set; } = "127.0.0.1";
    public ushort port { get; private set; } = 7777;
    public const string localHost = "127.0.0.1";
    public const ushort localPort = 7777;
    #endregion

    #region Constructor
    public NetworkDriverManager()
    {
        relayProvider = new RelayProvider();
        messageRouter = new MessageRouter(this);
        connectionManager = new ConnectionManager(this);

        relayProvider.OnUnityServiceInitialized += () => OnUnityServiceInitialized?.Invoke();
        relayProvider.OnJoinCodeGenerated += (string val) => OnJoinCodeGenerated?.Invoke(val);
        relayProvider.OnRelayError += (string val) => OnRelayError?.Invoke(val);
        messageRouter.OnBytesReceived += (NativeArray<byte> val) => OnBytesReceived?.Invoke(val);
    }
    #endregion

    #region Helpers
    bool StartHosting(ushort port)
    {
        if (driver.Bind(NetworkEndpoint.AnyIpv4.WithPort(port)) != 0)
        {
            Debug.LogError("Host failed to bind");
            return false;
        }

        if (driver.Listen() != 0)
        {
            Debug.LogError("Host failed to listen");
            return false;
        }

        Debug.Log($"Host is now listening on port {port}");

        connectionManager.SetConnectionId(1);
        IsHost = true;

        return true;
    }

    public void HostReceiveData()
    {
        DataStreamReader stream;
        NetworkEvent.Type evt;
        foreach (var kvpConnection in connections)
        {
            var targetKey = kvpConnection.Key;
            var targetConnection = kvpConnection.Value;
            if (!targetConnection.IsCreated) continue;

            while ((evt = targetConnection.PopEvent(driver, out stream)) != NetworkEvent.Type.Empty)
            {
                switch (evt)
                {
                    case NetworkEvent.Type.Data:
                        // Allocate a NativeArray of the correct length
                        NativeArray<byte> receivedData = new NativeArray<byte>(stream.Length, Allocator.Temp);

                        // Copy bytes from the DataStreamReader into the NativeArray
                        stream.ReadBytes(receivedData);
                        messageRouter.HostHandleReceivedData(receivedData);
                        break;
                    case NetworkEvent.Type.Connect:
                        //Debug.Log("Player Connected!");
                        //OnConnected?.Invoke(targetKey);
                        break;
                    case NetworkEvent.Type.Disconnect:
                        //connection = default; // mark connection as disconnected
                        connectionManager.RemoveConnectionSelf(); // mark connection as disconnected
                        Debug.Log("Player Disconnected!");
                        OnDisconnected?.Invoke(targetKey);
                        break;
                }
            }
        }
    }

    public void ClientReceiveData()
    {
        if (!connection.IsCreated) return;

        DataStreamReader stream;
        NetworkEvent.Type evt;

        while ((evt = connection.PopEvent(driver, out stream)) != NetworkEvent.Type.Empty)
        {
            switch (evt)
            {
                case NetworkEvent.Type.Data:
                    // Allocate a NativeArray of the correct length
                    NativeArray<byte> receivedData = new NativeArray<byte>(stream.Length, Allocator.Temp);

                    // Copy bytes from the DataStreamReader into the NativeArray
                    stream.ReadBytes(receivedData);
                    messageRouter.ClientHandleReceivedData(receivedData);
                    break;
                case NetworkEvent.Type.Connect:
                    Debug.Log("Connected to host!");
                    OnConnected?.Invoke(0);
                    break;
                case NetworkEvent.Type.Disconnect:
                    Debug.Log("Disconnected from host!");
                    OnDisconnected?.Invoke(0);
                    break;
            }
        }
    }
    #endregion

    #region Public Functions
    /// <summary>
    /// Initialize Unity Services, which allows the use of Unity Relay
    /// </summary>
    public async Task InitUnityServices()
    {
        await relayProvider.InitUnityServices();
    }

    /// <summary>
    /// Retrieves all available Relay regions from Unity Relay service.
    /// Fires the OnRegionsRetrieved event when done.
    /// </summary>
    public async Task<List<string>> GetRegions()
    {       
        return await relayProvider.GetRegions();
    }

    /// <summary>
    /// Hosts a Relay server with the specified maximum connections and region.
    /// </summary>
    /// <param name="maxConnections">Maximum number of players including host</param>
    /// <param name="region">Region ID string to host in (optional, can be null)</param>
    //public async Task<RelayServerData> HostRelay(int maxConnections = 2, string region = null)
    //{
    //    return await relayProvider.HostRelay(maxConnections, region);
    //}

    //public async Task<RelayServerData> JoinRelay(string joinCode)
    //{
    //    return await relayProvider.JoinRelay(joinCode);
    //}

    public async Task HostRelay(int maxConnections = 2, string region = null)
    {
        RelayServerData rsd = await relayProvider.HostRelay(maxConnections, region);
        var settings = new NetworkSettings();
        settings.WithRelayParameters(ref rsd);

        driver = NetworkDriver.Create(settings);
        reliablePipeline = driver.CreatePipeline(typeof(ReliableSequencedPipelineStage));

        if (!StartHosting(relayPort)) { return; }

        Debug.Log("Relay Host is now listening on port " + relayPort);
        joinCode = relayProvider.joinCode;
    }

    public void HostLocal(ushort port = localPort)
    {
        driver = NetworkDriver.Create();
        reliablePipeline = driver.CreatePipeline(typeof(ReliableSequencedPipelineStage));

        if (!StartHosting(port)) { return; }

        this.port = port;

        Debug.Log($"Host is now listening on port {port}");
    }

    public void StopHost()
    {
        // Disconnect all remote clients
        foreach (var connection in connections)
        {
            connection.Value.Disconnect(driver);
        }

        connections.Clear();

        // Close server socket
        driver.Dispose();

        // Reset state
        IsHost = false;
        this.port = localPort;
    }

    public async Task ConnectRelay(string joinCode)
    {
        RelayServerData rsd = await relayProvider.JoinRelay(joinCode);
        var settings = new NetworkSettings();
        settings.WithRelayParameters(ref rsd);

        driver = NetworkDriver.Create(settings);
        reliablePipeline = driver.CreatePipeline(typeof(ReliableSequencedPipelineStage));

        // Clients only connect (no bind needed for Relay).
        connectionManager.connection = driver.Connect();

        Debug.Log("Player client connecting to Relay server...");
        IsClient = true;
    }

    public async Task ConnectLocal(string ipAddress, ushort port = localPort)
    {
        var settings = new NetworkSettings();

        driver = NetworkDriver.Create(settings);
        reliablePipeline = driver.CreatePipeline(typeof(ReliableSequencedPipelineStage));

        // Parse IP
        var endpoint = NetworkEndpoint.Parse(ipAddress, port);

        connectionManager.connection = driver.Connect(endpoint);

        Debug.Log($"Client connecting to {ipAddress}:{port} ...");

        IsClient = true;

        this.ipAddress = ipAddress;
        this.port = port;

        await Task.CompletedTask;
    }

    public void Disconnect()
    {
        connection.Disconnect(driver);
        connectionManager.ResetConnectionId();
        this.ipAddress = localHost;
        this.port = localPort;
        driver.Dispose();
    }

    public void NetworkUpdate()
    {
        if (IsStarted)
        {
            messageRouter.NetworkUpdate();
        }
        if (IsHost)
        {
            connectionManager.RemoveNonConnections();
        }
        //if (IsHost)
        //{
        //    // 1. merge buffered input
        //    AppendBufferPayloads();

        //    // 2. sync connection state BEFORE sending
        //    SyncPayloadsWithConnections();

        //    // 3. send
        //    HostSendPayloads();

        //    // 4. cleanup
        //    RemoveNonConnections();
        //}

        //if (IsClient)
        //{
        //    AppendBufferPackets();
        //    ClientSendPayload();
        //}

        //OnNetworkUpdate?.Invoke();
    }

    public void AcceptClients()
    {
        NetworkConnection newConnection;
        while ((newConnection = driver.Accept()) != default(NetworkConnection))
        {
            int connectionId = connectionManager.AddConnection(newConnection);

            if (driver.BeginSend(reliablePipeline, newConnection, out var writer) == 0)
            {
                writer.WriteByte(1); // Intent
                writer.WriteInt(connectionId);
                writer.WriteShort((short)connections.Count);
                foreach (var kvp in connections)
                {
                    writer.WriteInt(kvp.Key);
                }
                writer.WriteInt(connectionId);
                driver.EndSend(writer);
                Debug.Log("Client connected! Total clients: " + connections.Count);
                //OnConnected?.Invoke(connectionId);
            }
            else
            {
                Debug.LogWarning($"Failed to send connection ID to client {connectionId}");
            }
        }
    }

    public void Shutdown()
    {
        if (driver.IsCreated)
        {
            driver.Dispose();
        }
    }

    public void Update()
    {
        if (!driver.IsCreated)
            return;

        driver.ScheduleUpdate().Complete();

        // RECEIVE ALWAYS AFTER DRIVER UPDATE
        if (IsHost)
        {
            HostReceiveData();
            AcceptClients();
        }

        if (IsClient)
        {
            ClientReceiveData();
        }
    }
    //void RemoveNonConnections()
    //{
    //    List<int> disconnectedKeys = new List<int>();
    //    foreach (var kvp in connections)
    //    {
    //        int clientId = kvp.Key;
    //        NetworkConnection targetconnection = kvp.Value;
    //        if (!targetconnection.IsCreated)
    //        {
    //            // Mark disconnected clients for removal
    //            disconnectedKeys.Add(clientId);
    //        }
    //    }
    //    // Remove disconnected clients
    //    foreach (var key in disconnectedKeys)
    //    {
    //        connections.Remove(key);
    //    }
    //}
    #endregion
}