using System.Collections.Generic;

using Unity.Networking.Transport.Relay;
using Unity.Collections;
using UnityEngine;
using Unity.Services.Relay;
using Unity.Services.Relay.Models;
using System.Buffers;
using System;
using System.Text;
using System.Collections.Concurrent;
using System.Threading.Tasks;
using Unity.Networking.Transport;

public class NetworkManager : MonoBehaviour
{
    #region Events
    /// <summary>
    /// Fired whenever the client has connected
    /// </summary>
    /// /// <param name="connectionId">Connection Id that Connected, 0 if client</param>
    public event Action<int> OnConnected;

    /// <summary>
    /// Fired whenever the client has disconnected
    /// </summary>
    /// /// /// <param name="connectionId">Connection Id that Disconnected, 0 if client</param>
    public event Action<int> OnDisconnected;

    /// <summary>
    /// Fired whenever there is a data sent from client or host
    /// </summary>
    /// <param name="data">Data sent</param>
    public event Action<NativeArray<byte>> OnBytesReceived;

    /// <summary>
    /// Fired when NetworkUpdate occurs
    /// </summary>
    public event Action OnNetworkUpdate;

    /// <summary>
    /// Fired when Unity Services (Authentication, Relay, etc.) have been successfully initialized.
    /// Subscribe to this event to perform actions once Unity Services are ready.
    /// </summary>
    public event Action OnUnityServiceInitialized;

    /// <summary>
    /// Fired when a Relay host has successfully created an allocation and generated a join code.
    /// The join code can be shared with other players to allow them to join the session.
    /// </summary>
    /// <param name="joinCode">The join code generated by the Relay service.</param>
    public event Action<string> OnJoinCodeGenerated;

    /// <summary>
    /// Fired whenever there is an error during Relay operations, such as initialization failure,
    /// host creation failure, or join failure. Use this to display error messages or log issues.
    /// </summary>
    /// <param name="errorMsg">A descriptive message indicating what went wrong with Relay.</param>
    public event Action<string> OnRelayError;
    #endregion

    #region Fields

    // Setup
    NetworkDriverManager networkDriverManager = new();

    // General
    public int connectionId { get { return networkDriverManager.connectionId; } }
    public string joinCode { get { return networkDriverManager.joinCode; } }
    public string ipAddress { get { return networkDriverManager.ipAddress; } }
    public ushort port { get { return networkDriverManager.port; } }

    // Server State
    public bool IsHost { get { return networkDriverManager.IsHost; } }
    public bool IsClient { get { return networkDriverManager.IsClient; } }
    public bool IsStarted { get { return networkDriverManager.IsStarted; } }
    public int PlayerCount { get { return networkDriverManager.PlayerCount; } }

    // Network Update
    [Header("Network Update")]
    public bool enableNetworkUpdate = true;
    public float networkUpdatePerSecond = 20f;
    float networkDelta;

    // --- Singleton ---
    public static NetworkManager networkManager { get; private set; }

    #endregion

    #region Listeners
    void Awake()
    {
        DontDestroyOnLoad(gameObject); // Persist across scenes
    }

    void Start()
    {
        networkManager = this;
        networkDriverManager.OnUnityServiceInitialized += () => OnUnityServiceInitialized?.Invoke();
        networkDriverManager.OnJoinCodeGenerated += (string val) => OnJoinCodeGenerated?.Invoke(val);
        networkDriverManager.OnRelayError += (string val) => OnRelayError?.Invoke(val);
        networkDriverManager.OnConnected += (int val) => OnConnected?.Invoke(val);
        networkDriverManager.OnDisconnected += (int val) => OnDisconnected?.Invoke(val);
        networkDriverManager.OnBytesReceived += (NativeArray<byte> val) => OnBytesReceived?.Invoke(val);
    }

    void Update()
    {
        if (enableNetworkUpdate)
        {
            networkDelta += Time.deltaTime;
            float interval = 1f / networkUpdatePerSecond;

            // FIXED TICK LOOP FIRST (deterministic network step)
            while (networkDelta >= interval)
            {
                networkDelta -= interval;
                NetworkUpdate();
            }
        }
        networkDriverManager.Update();
    }

    void OnDestroy()
    {
        networkDriverManager.Shutdown();
    }

    void OnApplicationQuit()
    {
        networkDriverManager.Shutdown();
    }
    #endregion

    #region Public Functions

    // --- Initialize ---

    /// <summary>
    /// Initializes Unity Services if they have not already been initialized. This must be called before hosting or connecting to a Relay session. Calling it multiple times is safe and will not reinitialize an already initialized service.
    /// </summary>
    public async void Init()
    {
        await networkDriverManager.InitUnityServices();
    }


    // --- Hosting, Connecting and Disconnecting ---

    /// <summary>
    /// Creates a Unity Relay allocation, retrieves a join code, configures the transport, and starts listening for incoming client connections. The local player becomes the host/server. 
    /// </summary>
    public async void HostRelay()
    {
        await networkDriverManager.HostRelay();
    }

    /// <summary>
    /// Starts a local host using Unity Transport without Relay.
    /// Creates a NetworkDriver, binds to the configured port,
    /// and begins listening for incoming client connections.
    /// </summary>
    public void HostLocal()
    {
        networkDriverManager.HostLocal();
    }

    /// <summary>
    /// Terminates the Relay allocation, disconnects all connected clients, stops accepting new connections, and clears host-side networking resources.
    /// </summary>
    public void StopHost()
    {
        networkDriverManager.StopHost();
    }

    /// <summary>
    /// Joins a Relay session using the supplied join code. This overload combines setting the join code and connecting in a single call.
    /// </summary>
    /// <param name="joinCode">The Unity Relay join code of the host session to join. This value is used immediately for the connection attempt.</param>
    public async Task ConnectRelay(string joinCode)
    {
        await networkDriverManager.ConnectRelay(joinCode);
    }

    /// <summary>
    /// Connects to a locally hosted server using the currently configured local network settings.
    /// Useful for local testing and development on the same machine or LAN.
    /// </summary>
    public async void ConnectLocal(string ipAddress = "127.0.0.1")
    {
        await networkDriverManager.ConnectLocal(ipAddress);
    }
    /// <summary>
    /// Connects to a locally hosted server using the currently configured local network settings.
    /// Useful for local testing and development on the same machine or LAN.
    /// </summary>
    public async void ConnectLocal(string ipAddress, ushort port)
    {
        await networkDriverManager.ConnectLocal(ipAddress, port);
    }

    /// <summary>
    /// Gracefully disconnects from the host, releases networking resources, clears connection state, and stops receiving network messages.
    /// </summary>
    public void Disconnect()
    {
        networkDriverManager.Disconnect();
    }


    // --- Process ---

    /// <summary>
    /// Performs a single networking update cycle. This processes incoming packets, connection events, disconnection events, and outgoing messages. Use this manually if automatic updates are disabled.
    /// </summary>
    public void NetworkUpdate()
    {
        networkDriverManager.NetworkUpdate();
        OnNetworkUpdate?.Invoke();
    }


    // --- For PlayerObjects ---

    /// <summary>
    /// Queues a byte payload to the specified connection. Typically used by the host to send data to an individual client.
    /// </summary>
    /// <param name="connectionId">The target connection identifier that should receive the data. Typically assigned by the networking system when a client connects.</param>
    /// <param name="data">The raw payload to send. Can contain serialized game state, RPC data, chat messages, or any custom packet format.</param>
    public void WriteDataTo(int connectionId, byte[] data)
    {
        networkDriverManager.messageRouter.WriteDataTo(connectionId, data);
    }

    /// <summary>
    /// Queues a "guaranteed" byte payload to the specified connection. Typically used by the host to send data to an individual client.
    /// </summary>
    /// <param name="connectionId">The target connection identifier that should receive the data. Typically assigned by the networking system when a client connects.</param>
    /// <param name="data">The raw payload to send. Can contain serialized game state, RPC data, chat messages, or any custom packet format.</param>
    public void WriteReliableDataTo(int connectionId, byte[] data)
    {
        networkDriverManager.messageRouter.WriteReliableDataTo(connectionId, data);
    }

    /// <summary>
    /// Sends a byte payload to every connected client except the local connection. Useful for relaying state updates received from one client to all other clients.
    /// </summary>
    /// <param name="data">The raw payload to broadcast to all connected remote clients except the local connection. Commonly used by a host to relay client messages to everyone else.</param>
    public void WriteDataToAllExceptSelf(byte[] data)
    {
        networkDriverManager.messageRouter.WriteDataToAllExceptSelf(data);
    }

    /// <summary>
    /// Sends a reliable byte payload to every connected client except the local connection. Useful for relaying "guaranteed" state updates received from one client to all other clients.
    /// </summary>
    /// <param name="data">The raw payload to broadcast to all connected remote clients except the local connection. Commonly used by a host to relay client messages to everyone else.</param>
    public void WriteReliableDataToAllExceptSelf(byte[] data)
    {
        networkDriverManager.messageRouter.WriteReliableDataToAllExceptSelf(data);
    }

    #endregion
}